require 'rake/testtask'

task :default => :test

Rake::TestTask.new do |t|
  ENV["TESTOPTS"] ||= "-v"
  t.libs << "lib"
  t.pattern = "test/*test.rb"
end

require 'test_bisect'
TestBisect::BisectTask.new
